### ISSUE TITLE
Anonymous user can create todo

### ISSUE THREAD

**Issue by poulp** [0xfoo/flask-todolist#1]
If this feature is wanted, the user has no way to recover its todo.

**Comment by 0xfoo** [comment]
The idea behind that is to allow a user to try the app, without the need to register.
Every todo is part of a todolist and thus you could access it through `{{URL}}/todolist/123`. So you could bookmark it and recover it that way.

But as anybody could make changes to this todolist, it is not very convenient. Nonetheless I think as far as showcasing goes, this is acceptable.

Thanks for the feedback!

**Comment by mbrookes** [comment]
I think it's fine to allow an anonymous user to create a todo list for the purpose of the demo, but lists created by registered users should only be accessible to that user. As it stands, you can go to any todolist created by a registered user and view or change it.

I was looking for a nice flask starter app for my teenage son, and flask-todolist is so, so close, but this gaping hole makes it unsuitable unfortunately.
